export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';
export const GET_COUNTRY_DETAIL_BORDERS = 'GET_COUNTRY_DETAIL_BORDERS';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_FILTER_VALUE = 'UPDATE_FILTER_VALUE';
export const UPDATE_FILTERED_COUNTRIES = 'UPDATE_FILTERED_COUNTRIES';
